### PR TITLE
Fix #221: Prevent panic on invalid BMP message length

### LINKED ISSUE #221: [bug] panic: runtime error: makeslice: len out of range
Saving this output here for visibility and future reference when troubleshooting:

```
E0518 21:13:59.110857       1 gobmpsrv.go:95] fail to recover BMP message Common Header with error: invalid version in common header, expected 3 found 241
panic: runtime error: makeslice: len out of range

goroutine 954 [running]:
github.com/sbezverk/gobmp/pkg/gobmpsrv.(*bmpServer).bmpWorker(0xc000024600, {0x972b30?, 0xc000012030})
        /workdir/pkg/gobmpsrv/gobmpsrv.go:99 +0x62e
created by github.com/sbezverk/gobmp/pkg/gobmpsrv.(*bmpServer).server
        /workdir/pkg/gobmpsrv/gobmpsrv.go:53 +0x16a
```

### PR DESCRIPTION
**Pull request by fenilp1**
- Close connection on Common Header parse errors instead of continuing
- Add bounds validation for MessageLength before allocating buffers
- Limit maximum message size to 1MB to prevent resource exhaustion
- Prevents panic when corrupted data contains invalid version or length fields

Fixes runtime error: makeslice: len out of range

### CODE REVIEW

File: pkg/gobmpsrv/gobmpsrv.go [hunk 1]
```diff
@@ -95,16 +95,22 @@ func (srv *bmpServer) bmpWorker(client net.Conn) {
 		header, err := bmp.UnmarshalCommonHeader(headerMsg[:bmp.CommonHeaderLength])
 		if err != nil {
 			glog.Errorf("fail to recover BMP message Common Header with error: %+v", err)
-			continue
+			return
+		}
+		// Validate message length before allocating (prevents panic on corrupted data)
+		msgLen := int(header.MessageLength) - bmp.CommonHeaderLength
+		if msgLen < 0 || msgLen > 1<<20 { // Max 1MB per BMP message
```
Comment (sbezverk) [inline pkg/gobmpsrv/gobmpsrv.go]: probably worth checking for (msgLen <= 0)

**Review by sbezverk — APPROVED** [review]
